--liquibase formatted sql

--changeset tispace:003-change-article-id-to-uuid
-- Note: UUID v7 generation will be handled by Hibernate/UuidV7Generator in the application
-- This migration changes the column type from BIGSERIAL to UUID

-- Create extension for UUID support
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Drop the old primary key constraint
ALTER TABLE articles DROP CONSTRAINT IF EXISTS articles_pkey;

-- Add new UUID column
ALTER TABLE articles ADD COLUMN id_new UUID;

-- Generate UUIDs for existing records (using UUID v4 as fallback for migration)
-- New records will use UUID v7 generated by the application
UPDATE articles SET id_new = gen_random_uuid()
WHERE id_new IS NULL;

-- Drop the old id column
ALTER TABLE articles DROP COLUMN IF EXISTS id;

-- Rename new column to id
ALTER TABLE articles RENAME COLUMN id_new TO id;

-- Set NOT NULL constraint
ALTER TABLE articles ALTER COLUMN id SET NOT NULL;

-- Recreate primary key
ALTER TABLE articles ADD PRIMARY KEY (id);

-- Drop the sequence that was used for BIGSERIAL (if exists)
DROP SEQUENCE IF EXISTS articles_id_seq CASCADE;

